In [50]:
import pandas as pd
from tqdm import tqdm

In [51]:
df_ground_truth = pd.read_csv("data/ground_truth.csv") #-data.csv")

In [52]:
df_ground_truth.shape

(1196, 2)

In [53]:
df_ground_truth.head()

                                            question  document
0  I’ve got about 25 minutes and some apples at h...         2
1  Can you suggest a quick applesauce recipe that...         2
2  I’ve got about an hour and a bunch of apples a...         5
3  Can you suggest a quick baked apple dessert us...         5
4  Got a few apples and butter at home — what’s a...         9

In [54]:
ground_truth = df_ground_truth.to_dict(orient="records")

In [55]:
from ingest import load_data, build_index

documents = load_data()
index = build_index(documents)

In [56]:
documents[0]

{'id': '2',
 'recipe_name': "Sarah's Homemade Applesauce",
 'total_time': '25 mins',
 'servings': '4',
 'ingredients': '4  apples - peeled, cored and chopped, ¾ cup water, ¼ cup white sugar, ½ teaspoon ground cinnamon',
 'directions': "Combine apples, water, sugar, and cinnamon in a saucepan; cover and cook over medium heat until apples are soft, about 15 to 20 minutes.\nAllow apple mixture to cool, then mash with a fork or potato masher until it is the consistency you like.\n\n\n\n\n\n\n\n\n\n\n\nPhoto by cookin'mama.\ncookin mama\n",
 'nutrition': 'Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohydrate 32g 12%, Dietary Fiber 4g 13%, Total Sugars 27g, Protein 0g, Vitamin C 6mg 32%, Calcium 13mg 1%, Iron 0mg 1%, Potassium 150mg 3%'}

In [70]:
boost = {'total_time': 1.0, 'ingredients': 3.0}

index.search(
    "Any quick apple dessert or snack recipe with just apples, sugar, cinnamon, and water?",
    num_results=5,
    boost_dict=boost
)

[{'id': '126',
  'recipe_name': 'Apple Cinnamon Oatmeal Muffins',
  'total_time': '35 mins',
  'servings': '12',
  'ingredients': '¼ cup quick-cooking oats, 1 tablespoon brown sugar, 1 tablespoon melted butter, ¼ teaspoon ground cinnamon',
  'directions': 'Preheat the oven to 400 degrees F (200 degrees C). Grease a 12-cup muffin pan or line with paper liners.\nMake topping: Mix oats, brown sugar, melted butter, and cinnamon in a small bowl; set aside.\nMake muffins: Whisk together oats, flour, brown sugar, cinnamon, baking powder, baking soda, and salt in a large bowl. Whisk together applesauce, milk, oil, egg, and vanilla extract in a medium bowl. Stir applesauce mixture into flour mixture until all ingredients are moistened. Fold in chopped apple.\nSpoon batter into the prepared muffin cups about 2/3 full; sprinkle oat topping mixture evenly over each muffin.\nBake in the preheated oven until a toothpick inserted near the center comes out clean, about 15 minutes.',
  'nutrition': 'Total Fat 7g 9%, Saturated Fat 2g 9%, Cholesterol 19mg 6%, Sodium 210mg 9%, Total Carbohydrate 30g 11%, Dietary Fiber 2g 8%, Total Sugars 10g, Protein 4g, Vitamin C 1mg 4%, Calcium 56mg 4%, Iron 1mg 8%, Potassium 111mg 2%'},
 {'id': '2',
  'recipe_name': "Sarah's Homemade Applesauce",
  'total_time': '25 mins',
  'servings': '4',
  'ingredients': '4  apples - peeled, cored and chopped, ¾ cup water, ¼ cup white sugar, ½ teaspoon ground cinnamon',
  'directions': "Combine apples, water, sugar, and cinnamon in a saucepan; cover and cook over medium heat until apples are soft, about 15 to 20 minutes.\nAllow apple mixture to cool, then mash with a fork or potato masher until it is the consistency you like.\n\n\n\n\n\n\n\n\n\n\n\nPhoto by cookin'mama.\ncookin mama\n",
  'nutrition': 'Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohydrate 32g 12%, Dietary Fiber 4g 13%, Total Sugars 27g, Protein 0g, Vitamin C 6mg 32%, Calcium 13mg 1%, Iron 0mg 1%, Potassium 150mg 3%'},
 {'id': '33',
  'recipe_name': "Sarah's Homemade Applesauce",
  'total_time': '25 mins',
  'servings': '4',
  'ingredients': '4  apples - peeled, cored and chopped, ¾ cup water, ¼ cup white sugar, ½ teaspoon ground cinnamon',
  'directions': "Combine apples, water, sugar, and cinnamon in a saucepan; cover and cook over medium heat until apples are soft, about 15 to 20 minutes.\nAllow apple mixture to cool, then mash with a fork or potato masher until it is the consistency you like.\n\n\n\n\n\n\n\n\n\n\n\nPhoto by cookin'mama.\ncookin mama\n",
  'nutrition': 'Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohydrate 32g 12%, Dietary Fiber 4g 13%, Total Sugars 27g, Protein 0g, Vitamin C 6mg 32%, Calcium 13mg 1%, Iron 0mg 1%, Potassium 150mg 3%'},
 {'id': '64',
  'recipe_name': "Sarah's Homemade Applesauce",
  'total_time': '25 mins',
  'servings': '4',
  'ingredients': '4  apples - peeled, cored and chopped, ¾ cup water, ¼ cup white sugar, ½ teaspoon ground cinnamon',
  'directions': "Combine apples, water, sugar, and cinnamon in a saucepan; cover and cook over medium heat until apples are soft, about 15 to 20 minutes.\nAllow apple mixture to cool, then mash with a fork or potato masher until it is the consistency you like.\n\n\n\n\n\n\n\n\n\n\n\nPhoto by cookin'mama.\ncookin mama\n",
  'nutrition': 'Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohydrate 32g 12%, Dietary Fiber 4g 13%, Total Sugars 27g, Protein 0g, Vitamin C 6mg 32%, Calcium 13mg 1%, Iron 0mg 1%, Potassium 150mg 3%'},
 {'id': '95',
  'recipe_name': "Sarah's Homemade Applesauce",
  'total_time': '25 mins',
  'servings': '4',
  'ingredients': '4  apples - peeled, cored and chopped, ¾ cup water, ¼ cup white sugar, ½ teaspoon ground cinnamon',
  'directions': "Combine apples, water, sugar, and cinnamon in a saucepan; cover and cook over medium heat until apples are soft, about 15 to 20 minutes.\nAllow apple mixture to cool, then mash with a fork or potato masher until it is the consistency you like.\n\n\n\n\n\n\n\n\n\n\n\nPhoto by cookin'mama.\ncookin mama\n",
  'nutrition': 'Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohydrate 32g 12%, Dietary Fiber 4g 13%, Total Sugars 27g, Protein 0g, Vitamin C 6mg 32%, Calcium 13mg 1%, Iron 0mg 1%, Potassium 150mg 3%'}]

In [84]:
def text_search(query):
    boost_dict = {'total_time': 1.0, 'ingredients': 1.0}

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict
    )

In [88]:
def compute_relevance(q, search_function):
    doc_id = q["document"]
    print(doc_id)
    results = search_function(query=q["question"])

    relevance = []
    for d in results:
        print(d["id"])
        relevance.append(int(int(d["id"]) == int(doc_id)))

    return relevance

In [89]:
def compute_relevance_total(ground_truth, search_function):
    relevance_total = []

    for q in tqdm(ground_truth):
        relevance = compute_relevance(q, search_function)
        relevance_total.append(relevance)

    return relevance_total

In [90]:
compute_relevance_total(ground_truth[:10], text_search)

100%|██████████| 10/10 [00:00<00:00, 61.67it/s]

2
2
64
33
95
112
2
127
764
353
326
512
5
5
67
36
98
120
5
426
136
11
73
42
9
1042
493
71
9
102
9
677
621
665
24
117
10
140
417
852
136
1041
10
1058
852
619
1041
17
11
142
86
55
24
117
11
1058
852
1041
126
431

[[1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [91]:
relevance_total = compute_relevance_total(ground_truth, text_search)

  1%|▏         | 15/1196 [00:00<00:08, 138.92it/s]

2
2
64
33
95
112
2
127
764
353
326
512
5
5
67
36
98
120
5
426
136
11
73
42
9
1042
493
71
9
102
9
677
621
665
24
117
10
140
417
852
136
1041
10
1058
852
619
1041
17
11
142
86
55
24
117
11
1058
852
1041
126
431
14
493
1042
40
9
102
14
126
677
593
624
621
16
58
27
89
120
110
16
14
76
45
107
78
17
17
48
79
110
414
17
1041
852
1067
624
126
19
808
19
50
112
81
19
619
852
1041
19
50
20
20
51
82
113
117
20
677
621
852
593
619
24
55
86
117
24
28
24
126
86
55
24
117
26
26
57
119
88
839
26
88
26
119
57
852
27
27
120
58
89
1041
27
58
120
89
27
17
28
55
86
117
24
779
28

  4%|▎         | 43/1196 [00:00<00:08, 134.97it/s]

808
852
353
631
140
29
142
60
29
122
91
29
852
619
764
529
1058
30
493
1042
123
92
61
30
61
30
92
123
677
33
808
2
64
95
33
33
142
126
29
60
122
36
852
1041
5
36
67
36
1064
307
27
58
120
40
1042
493
142
9
40
40
677
621
1058
593
1064
41
417
140
624
852
142
41
140
621
677
593
147
42
142
24
117
55
86
42
852
163
768
619
683
45
493
1042
142
71
40
45
677
621
796
1041
852
47
27
58
89
120
677
47
27
89
58
120
1052
48
48
79
110
17
27
48
58
120
27
89
48
50
50
81
112
19
808
50
529
136
761
42
73
51
126
55
117
24
86
51
1042
493
1064
764
941
55
24
55
86
117
758
55
431
126
24
55
86
57

  6%|▌         | 70/1196 [00:00<00:09, 124.29it/s]

126
131
119
57
26
57
764
213
353
136
619
58
27
120
58
89
1041
58
677
621
593
353
852
59
55
86
24
117
28
59
677
621
593
1058
746
60
136
29
122
60
91
60
142
29
122
60
91
61
493
1042
260
123
30
61
92
123
30
61
619
64
493
1042
40
9
102
64
142
2
33
95
64
67
852
271
1041
122
29
67
126
60
29
91
122
71
9
40
71
102
493
71
142
431
126
29
122
72
417
140
142
852
29
72
140
417
852
410
147
73
11
42
73
104
142
73
136
326
849
353
852
76
1042
493
14
45
107
76
142
29
91
60
122
78
58
89
120
27
79
78
60
29
91
122
120
79
48
17
79
110
414
79
17
110
48
79
135
81

  8%|▊         | 99/1196 [00:00<00:08, 127.50it/s]

50
112
81
19
808
81
19
50
81
112
619
82
24
117
55
86
82
82
142
20
113
51
82
86
117
55
86
24
59
86
1058
24
55
117
86
88
26
88
119
57
131
88
26
88
119
57
146
89
27
120
89
58
1041
89
58
27
120
89
17
90
86
55
117
24
90
90
677
621
353
593
619
91
136
852
124
29
60
91
24
55
86
117
852
92
30
92
123
61
1042
92
677
621
529
123
61
95
808
2
33
64
95
95
353
29
122
60
91
98
142
24
117
55
86
98
683
619
120
58
89
102
493
1042
142
9
71
102
1041
136
721
746
665
103
417
140
852
1041
761
103
621
852
677
353
593
104
852
1041
136
1024
601
104
768
163
852
999
336
107
1042
493
9
40
71
107

 11%|█         | 128/1196 [00:00<00:08, 130.54it/s]

142
1041
60
122
29
109
58
27
89
120
16
109
353
660
126
140
326
110
17
48
79
110
414
110
136
1041
142
619
1067
112
50
81
19
112
808
112
512
683
142
353
796
113
82
20
51
113
142
113
677
621
1041
368
593
117
55
86
117
24
28
117
126
24
117
86
55
119
119
57
88
26
126
119
136
142
48
17
110
120
27
120
58
89
665
120
624
58
89
120
27
121
55
86
117
24
676
121
59
28
90
121
126
122
136
852
124
11
73
122
142
60
122
29
91
123
1042
493
92
123
30
123
1058
949
529
999
326
124
124
849
762
307
278
124
124
29
122
91
60
126
126
839
524
765
211
126
126
127
24
55
117
127
127
750
876
860
918
127
856
486
750
127
876
129
129
55
117
24
86
129
982
975
619
949
984
130

 13%|█▎        | 157/1196 [00:01<00:08, 120.08it/s]

60
122
29
91
136
130
426
852
353
11
42
131
26
57
88
119
999
131
136
619
353
14
76
134
134
852
1041
568
42
134
134
852
986
163
768
135
17
110
79
48
89
135
17
79
110
48
619
136
136
1041
120
27
89
136
353
852
529
1058
326
137
137
873
176
821
353
137
137
764
665
1058
439
140
326
129
534
213
200
140
619
796
852
1041
48
141
141
852
9
40
71
141
621
677
852
353
593
142
1042
493
142
9
40
142
764
619
796
146
17
144
144
1058
11
73
104
144
136
29
122
60
91
145
145
885
910
1020
428
145
145
999
664
619
136
146

 14%|█▍        | 170/1196 [00:01<00:08, 122.44it/s]

146
808
112
19
81
146
536
898
764
761
11
147
140
417
852
147
1041
147
140
147
417
11
104
148
148
486
462
856
769
148
570
950
148
769
856
150
150
721
1041
930
842
150
150
1041
721
234
89
152
1001
152
910
161
176
152
152
150
27
120
58
154
170
154
340
337
761
154
154
340
223
1058
849
161
1001
910
161
711
512
161
200
322
353
808
984
163
163
768
332
265
878
163
163
768
181
765
881
166
807
690
246
166
271
166
916
1058
560
368
687
169

 16%|█▋        | 195/1196 [00:01<00:09, 105.26it/s]

150
852
1041
197
200
169
169
367
1058
150
873
170
170
154
340
200
353
170
154
340
170
619
768
171
171
120
58
27
89
171
852
529
683
650
1041
172
172
663
150
665
940
172
172
721
663
746
150
176
220
176
873
821
1050
176
150
1058
764
176
210
177
177
326
200
925
213
177
677
721
213
326
621
181
181
710
307
849
197
181
181
163
768
765
881
185
1042
493
185
764
260
185
185
852
949
534
958
189
189
27
58
120
89
189
189
353
150
48
17
190
1084
190
952
873
1058
190
1067
1017
627
1084
190
197
197
762
278
849
307
197
746
197
764
676
769
198
198
367
668
962
534
198
949
852
1041
761
353
200

 18%|█▊        | 219/1196 [00:01<00:09, 108.42it/s]

200
326
213
177
925
200
200
326
213
925
177
202
200
171
177
202
660
202
150
152
852
89
58
206
1042
493
513
553
817
206
213
207
331
243
234
207
332
207
826
226
768
207
207
206
232
817
241
208
208
380
1021
594
719
208
807
621
687
600
601
209
209
234
215
721
1041
209
209
210
228
215
325
210
210
213
779
486
676
210
210
213
234
241
1058
211
211
1075
235
839
233
211
211
621
677
213
353
212
1001
910
212
241
711
212
212
353
126
431
210
213
213
200
210
326
486
213
326
213
200
925
177
215
215
721
234
329
665
215
220
215
209
232
210
217
211
217
235
233
1015
217
213
852
211
1041
226
220
220
873
176
821
782
220
220
210
999
885
619
221
1042
493
817
260
288
221

 21%|██        | 246/1196 [00:02<00:07, 119.34it/s]

493
1042
288
260
764
223
1001
910
223
241
711
223
223
852
228
210
337
224
224
765
305
126
839
224
213
761
888
224
226
225
225
213
779
676
210
225
225
210
233
207
568
226
332
226
933
229
163
226
226
241
232
206
234
228
332
228
226
529
229
228
241
206
228
553
513
229
332
229
529
226
440
229
229
677
621
260
553
230
230
228
210
226
241
230
1058
849
353
271
213
231
687
231
629
719
166
231
231
594
1021
629
732
232
232
444
854
339
808
232
852
680
353
1041
209
233
233
211
1075
126
235
233
529
233
619
796
910
234
234
980
969
721
842
234
1058
234
1064
48
110
235
235
765
211
1047
998
235
1044
1058
235
764
238
238
238
1042
493
260
764
238
493
1042
238
260
764
241

 23%|██▎       | 274/1196 [00:02<00:08, 113.92it/s]

241
513
553
206
817
241
241
228
206
553
513
242
332
229
207
242
826
242
163
768
529
336
229
243
243
808
339
854
444
243
243
210
232
228
336
245
245
1041
721
392
234
245
852
703
353
1041
336
246
246
278
687
849
690
246
1021
594
677
690
621
247
332
247
282
265
286
247
910
885
145
1020
428
249
260
1042
493
261
264
249
270
288
271
260
849
250
278
250
246
272
274
250
250
1058
979
687
842
251
687
251
253
986
807
251
687
251
849
986
277
253
253
841
808
926
444
253
353
916
326
849
1058
254
1042
493
929
288
260
254
254
264
260
253
261
255

 25%|██▌       | 299/1196 [00:02<00:07, 116.46it/s]

255
873
353
270
1058
255
255
254
253
273
293
256
849
271
277
687
253
256
256
254
255
271
253
258
258
721
89
120
27
258
796
511
163
768
949
260
493
1042
260
288
261
260
836
796
213
682
317
261
260
261
493
1042
288
261
677
621
1058
593
619
262
262
668
326
367
213
262
288
265
290
282
529
264
493
260
1042
288
261
264
264
255
261
273
260
265
265
332
948
286
972
265
265
605
732
271
288
267
1041
721
267
665
273
267
278
270
267
246
605
269
269
762
253
687
500
269
474
916
935
509
535
270
270
873
353
1058
706
270
270
250
254
253
852
271
253
271
687
251
1046
271
271
293
348
282
929
272
272
849
762
807
687
272

 27%|██▋       | 325/1196 [00:02<00:07, 120.70it/s]

272
250
354
601
1024
273
273
721
851
258
842
273
910
885
145
1020
428
274
278
274
357
246
1041
274
677
621
317
353
852
276
253
271
849
277
687
276
276
262
687
1058
265
277
277
271
687
849
762
277
254
270
253
265
273
278
278
246
986
849
762
278
278
246
274
250
280
280
278
246
280
353
274
280
278
246
280
274
1058
282
332
265
254
282
650
282
332
282
247
265
286
286
332
286
265
644
254
286
286
273
260
288
535
288
288
1042
260
493
264
288
916
210
443
933
529
289
332
289
650
286
265
289
332
265
286
529
254
290
290
270
255
873
821
290
145
910
885
1020
293
291
213
200
779
694
367
291
910
145
885
1020
428
293
293
282
288
251
271
293
885
145
910
1020
428
294

 29%|██▉       | 352/1196 [00:02<00:06, 125.33it/s]

294
293
282
277
271
294
677
265
288
621
282
295
295
312
276
687
251
295
295
687
290
627
265
296
296
307
343
849
312
296
296
306
337
298
332
298
332
878
298
265
853
298
298
332
278
324
326
299
299
294
1058
278
326
299
154
340
502
254
764
301
332
301
298
715
878
301
301
345
621
677
849
303
303
246
660
322
307
303
303
1058
353
326
265
304
304
493
1042
764
337
304
304
326
335
761
330
305
305
765
224
126
507
305
677
621
842
761
721
306
306
324
332
322
298
306
306
332
337
761
996
307
307
846
432
849
343
307
307
432
832
243
917
309
309
493
1042
777
1064
309
721
150
737
746
1041
310
310
844
721
338
136
310
310
654
844
349
334
311
1001
311
910
711
241
311

 32%|███▏      | 378/1196 [00:03<00:06, 119.81it/s]

311
326
213
930
925
312
312
849
295
748
1046
312
312
320
229
748
325
315
315
331
307
849
343
315
271
1067
265
788
695
317
1001
317
910
327
711
317
338
522
335
317
696
320
229
320
353
325
529
320
949
320
910
619
271
322
322
389
202
86
117
322
322
852
306
353
326
324
303
619
104
42
11
324
852
662
683
1041
619
325
1001
325
910
241
852
325
1001
910
317
335
937
326
326
925
200
213
177
326
326
761
58
89
120
327
1001
910
317
327
711
327
327
317
696
522
338
328
328
849
762
303
307
328
328
945
953
677
621
329
721
329
842
930
737
329
336
326
593
329
345
330

 34%|███▍      | 407/1196 [00:03<00:06, 129.41it/s]

330
213
326
345
200
330
336
677
326
621
652
331
315
331
849
307
343
331
677
331
621
593
315
332
332
996
878
163
768
332
332
996
677
762
232
334
332
529
229
535
391
334
335
334
242
312
320
335
335
1001
910
711
241
335
335
322
660
317
683
336
332
336
506
301
878
336
336
796
326
163
768
337
493
1042
337
324
304
337
337
322
677
324
332
338
338
310
696
721
215
338
317
677
621
338
522
339
339
808
444
854
926
339
339
210
761
309
762
340
340
154
334
312
303
340
223
154
340
299
849
342
332
342
301
535
265
342
1058
335
764
846
714
343
343
225
309
353
761
343
322
343
353
278
324
345
345
761
808
444
339
345
345
761
326
309
329
347
1001
910
425
347
176
347
431
511
347
425
677
348
348
353
873
821
290
348

 35%|███▌      | 421/1196 [00:03<00:05, 130.08it/s]

348
929
1058
247
271
349
349
808
339
444
926
349
349
621
677
593
317
350
367
350
385
389
326
350
368
245
353
852
377
352
357
389
386
352
368
352
353
703
949
852
999
353
353
873
359
821
417
353
368
677
377
392
399
354
601
354
1024
807
621
354
511
687
246
619
1021
356
356
368
852
245
377
356
353
368
392
399
357
357
368
357
352
852
1041
357
1058
852
975
1041
764
359
359
368
392
377
399
359
359
1058
368
230
353
361
1001
910
852
241
361
361
368
852
1041
353
392
362
362
399
359
353
873
362

 37%|███▋      | 447/1196 [00:03<00:06, 110.57it/s]

677
621
271
703
593
367
367
326
213
389
676
367
719
367
368
474
377
368
368
852
353
245
377
368
368
353
388
377
399
374
368
374
353
361
388
374
368
353
388
392
374
377
377
808
854
232
664
377
245
368
619
377
392
380
380
1021
594
368
353
380
768
163
594
1021
1032
382
368
388
392
852
353
382
1058
352
703
389
399
385
385
350
367
86
24
385
368
353
377
126
1058
386
386
839
765
235
233
386
665
126
703
353
399
388
368
388
392
353
377
388
377
245
368
392
353
389
389
171
202
728
385
389
352
389
171
399
703
391
332
391
933
229
826
391
933
255
929
353
368
392
392
1041
721
245
665
392
392
624
399
377
368
394
394
807
601
1024
354
394

 40%|███▉      | 475/1196 [00:03<00:05, 121.17it/s]

621
394
627
677
593
399
399
359
873
353
362
399
399
849
1040
353
703
410
417
410
873
353
190
410
511
852
508
426
221
414
414
511
508
48
110
414
414
511
17
110
79
417
417
410
873
635
821
417
677
621
852
221
593
419
419
417
511
852
642
419
511
126
665
619
353
422
511
436
852
417
1041
422
769
957
189
422
1005
423
511
431
852
417
353
423
353
873
410
821
423
425
1001
910
425
347
711
425
1001
910
425
347
176
426
511
426
1041
852
211
426
664
317
808
1064
982
427
1001
797
721
89
27
427
534
439
668
200
326
428
428
145
885
910
1020
428
428
619
650
425
347
430
511
852
624
436
426
430
524
511
627
852
377
431
852
431
511
436
619
431
136
431
124
511
619
432

 42%|████▏     | 501/1196 [00:04<00:05, 121.74it/s]

432
307
500
498
1029
432
432
1058
508
849
326
436
511
1058
417
764
664
436
431
436
511
619
426
437
332
437
226
878
265
437
677
621
593
619
910
439
439
676
779
200
326
439
353
326
534
849
619
440
332
440
449
718
768
440
332
440
229
449
535
442
442
808
444
50
112
442
721
267
665
797
785
443
443
761
808
841
112
443
443
808
841
444
339
444
444
339
451
442
664
444
444
446
677
511
621
445
126
445
446
386
839
445
431
445
511
1058
764
446
446
126
839
444
211
446
446
444
288
440
677
449
332
449
718
440
229
449
534
817
207
826
535
451
451
339
444
808
854
451
451
120
27
58
89
454
463
454
873
821
684
454
677
621
468
1058
593
457

 44%|████▍     | 528/1196 [00:04<00:05, 125.96it/s]

493
1042
457
764
260
457
457
683
1015
454
949
458
468
852
463
322
683
458
353
267
326
352
1024
459
459
312
468
276
748
459
459
619
796
768
163
461
458
461
454
468
463
461
852
352
458
461
389
462
148
462
856
486
769
462
486
462
769
918
148
463
353
873
463
821
454
463
463
458
808
322
468
464
808
854
464
19
50
464
464
454
986
619
134
468
468
1047
839
1053
524
468
468
206
474
935
916
470
470
873
1027
821
1058
470
852
619
482
489
1058
474
511
368
150
245
431
474
474
677
353
621
808
476
476
489
849
762
1046
476
476
665
628
551
42
482
852
482
322
271
986
482
624
769
945
888
368
486
486
213
200
534
210
486
462
486
677
621
468
489
489
849
476
307
762
489
489
89
27
120
58
493

 46%|████▋     | 554/1196 [00:04<00:05, 124.66it/s]

493
1042
270
764
260
493
493
1040
529
904
1064
498
498
1046
500
621
807
498
498
1046
807
500
600
500
500
621
677
849
498
500
440
500
288
442
446
502
502
312
508
748
299
502
502
312
536
508
1058
503
332
503
650
529
535
503
510
650
503
520
529
505
505
332
529
535
650
505
746
505
769
764
1064
506
332
506
535
449
229
506
524
506
508
553
513
507
507
839
524
126
765
507
507
677
980
621
975
508
332
511
229
228
529
508
440
508
535
1064
437
509
509
687
807
986
849
509
509
687
762
511
307
510
660
500
511
307
762
510
520
510
508
731
278
511
511
509
849
307
1046
511
511
524
508
142
322
512
512
1001
910
533
711
512
512
368
761
950
928
513
513
553
1042
493
817
513

 49%|████▊     | 583/1196 [00:04<00:04, 123.05it/s]

513
553
817
206
1046
515
515
320
278
1047
293
515
719
619
512
431
502
519
519
554
1017
842
1032
519
519
554
765
999
836
520
510
520
731
529
511
520
520
510
508
525
522
521
1001
910
521
241
711
521
521
917
529
621
677
522
524
765
839
233
507
522
522
338
508
704
511
523
1042
493
553
513
260
523
260
523
440
535
261
524
524
1053
507
839
386
524
852
511
522
508
999
525
493
1042
525
523
764
525
336
508
525
522
243
529
332
529
826
207
229
529
500
508
535
353
523
530
530
849
271
802
307
530
619
530
98
5
67
532
532
575
661
721
89
532
532
575
535
832
661
533
1001
533
910
241
711
533
533
849
345
301
326
534
534
367
668
200
210
534
534
832
677
621
535
535

 51%|█████     | 610/1196 [00:05<00:04, 126.43it/s]

535
332
529
229
391
535
535
832
661
89
58
536
536
898
808
709
444
536
536
898
1058
278
764
541
541
306
1001
557
560
541
541
553
513
548
220
545
545
721
574
842
1082
545
852
808
353
1041
1058
548
628
839
765
446
386
548
513
553
551
548
561
549
549
1041
721
575
532
549
796
163
768
579
326
550
808
619
444
339
1045
550
541
550
553
513
852
551
1001
551
910
241
711
551
126
551
586
665
353
553
553
513
817
493
1042
553
1042
493
513
553
260
554
554
519
536
898
529
554
554
836
769
958
888
555
555
616
962
534
1017
555
541
852
1041
548
553
557
1042
493
557
764
1064
557
557
315
852
1041
511
560
1001
910
560
241
425
560
553
513
621
541
677
561
561
1046
762
307
802
561
561
933
565
553
513
565

 53%|█████▎    | 637/1196 [00:05<00:04, 127.19it/s]

565
873
579
821
353
565
677
565
621
353
593
568
849
762
986
307
684
568
568
1058
548
353
549
570
721
665
1082
574
545
570
577
548
549
852
561
571
1001
910
711
852
512
571
1001
910
711
317
852
574
574
1041
721
1067
545
574
17
110
79
48
1067
575
575
532
120
89
27
575
661
575
532
721
842
577
549
721
1082
575
532
577
852
1041
943
337
431
579
579
821
873
176
417
579
579
541
1058
1064
577
583
590
583
628
591
588
583
619
583
627
591
628
584
584
686
593
632
58
584
593
584
686
632
677
586
586
1042
493
1064
764
586
1042
493
586
260
288
588
126
588
628
583
609
588
621
593
677
619
476
590
1001
910
317
551
721
590
624
619
1067
586
999
591
628
583
590
591
609
591

 56%|█████▌    | 667/1196 [00:05<00:03, 134.08it/s]

621
677
593
586
949
593
593
621
677
632
807
593
593
584
632
686
677
594
594
1021
380
629
620
594
594
1021
719
380
662
596
596
1022
600
690
594
596
1067
89
120
27
58
597
597
619
624
586
616
597
909
583
597
619
171
600
600
807
1046
687
703
600
807
621
600
677
593
601
601
354
1024
807
621
601
594
1021
354
601
1024
603
603
1001
910
551
803
603
603
616
632
593
949
604
604
117
55
24
86
604
604
796
627
999
949
605
732
605
380
807
594
605
687
380
353
619
796
606
606
604
86
24
117
606
619
627
999
606
134
607
332
607
265
535
226
607
607
953
777
732
605
609
609
590
999
628
583
609
1058
605
732
807
635
613
332
878
265
614
853
613
619
732
605
807
796
614
614
326
606
619
586
614
796
619
677
586
593
616
616
555
389
962
326
616

 57%|█████▋    | 681/1196 [00:05<00:03, 135.67it/s]

635
616
603
1045
1058
617
617
873
353
821
417
617
619
617
586
596
1022
619
808
619
339
444
761
619
627
943
353
812
605
620
849
687
807
620
986
620
1021
594
620
680
686
621
621
593
677
807
354
621
677
621
593
687
632
623
332
623
948
163
768
623
623
58
120
27
89
624
614
624
606
586
134
624
614
624
958
368
769
626
808
619
444
626
339
626
586
353
126
982
949
627
627
807
732
605
649
627
627
601
1024
354
812
628
628
126
590
999
609
628
27
120
89
58
586
629

 59%|█████▉    | 707/1196 [00:05<00:04, 111.35it/s]

629
594
1021
380
320
629
380
586
1021
594
1032
631
631
326
606
1017
55
631
619
999
631
796
1058
632
632
593
687
986
621
632
593
584
686
621
632
635
635
417
873
353
821
635
619
586
627
607
812
639
639
807
1046
649
600
639
621
639
677
807
662
642
642
688
24
86
117
642
666
1058
619
662
642
643
1001
643
910
711
241
643
643
668
769
918
842
644
332
644
529
1054
229
644
493
1042
260
553
513
645
732
605
661
719
645
645
732
605
535
661
832
649
762
649
687
849
632
649
213
353
317
808
788
650
332
650
853
878
535
650
271
979
796
512
764
652
493
1042
652
260
656
652
652
1058
353
511
849
653
417
653
140
1041
852
653
677
524
621
854
353
654

 61%|██████▏   | 735/1196 [00:06<00:03, 121.02it/s]

1001
910
654
711
771
654
654
706
796
662
658
656
493
1042
656
764
1064
656
656
798
437
762
996
658
658
1032
278
594
1021
658
1041
852
658
649
197
660
660
326
367
734
728
660
660
1052
1039
1058
732
661
661
721
532
575
665
661
661
721
532
575
665
662
807
662
621
687
649
662
958
317
662
719
368
663
663
172
665
721
940
663
1045
624
663
852
1058
664
852
664
1041
762
605
664
949
762
664
353
332
665
665
721
661
746
785
665
677
621
796
1058
1041
666
666
1021
594
644
656
666
666
677
594
1021
621
668
668
779
213
210
697
668
668
721
513
553
535
669
669
676
1017
668
779
669
677
669
621
701
779
676
676
326
669
213
734
676
676
210
779
669
389
677
677
621
687
620
710
677

 64%|██████▍   | 764/1196 [00:06<00:03, 128.14it/s]

677
621
593
690
687
678
1001
910
678
711
241
678
678
326
747
721
793
680
1021
594
680
687
620
680
680
1021
594
677
1032
682
493
1042
764
682
260
682
682
677
621
668
786
683
332
650
265
878
535
683
719
683
779
814
271
684
684
873
706
1058
417
684
910
145
885
1020
428
686
686
593
677
584
1021
686
686
584
593
690
779
687
687
710
684
807
703
687
145
885
1020
910
428
688
676
24
117
86
55
688
690
688
353
814
126
690
690
687
166
620
807
690
594
1021
509
1032
1024
694
694
213
200
534
779
694
694
677
704
814
696
695
695
701
682
265
36
695
680
687
710
703
779
696
696
721
338
842
665
696
696
522
210
682
715
697
697
668
326
213
779
697
697
336
839
535
243
701
852
701
1041
197
761
701
852
701
1041
601
354
703

 66%|██████▋   | 793/1196 [00:06<00:03, 130.88it/s]

703
687
690
710
786
703
703
687
710
601
354
704
694
688
779
697
668
704
317
704
696
650
677
706
706
844
835
89
27
706
706
873
821
837
782
709
709
808
339
444
854
709
709
682
334
719
714
710
687
710
807
849
1046
710
710
687
150
680
627
711
711
1001
910
654
241
711
680
534
706
714
711
713
762
849
786
710
687
713
710
687
713
677
684
714
1042
493
714
764
1064
714
714
703
678
676
1087
715
332
715
834
535
286
715
814
668
779
715
721
716
332
716
650
715
853
716
668
289
849
682
814
718
332
718
449
440
163
718
718
792
682
440
719
719
719
594
1021
1032
166
719
719
605
732
690
687
721
721
842
737
930
329
721
200
213
842
721
808
722
722
288
446
440
724
722
605
732
724
719
746
724

 69%|██████▊   | 821/1196 [00:06<00:02, 131.52it/s]

724
786
762
271
307
724
677
353
621
1064
213
728
728
758
734
660
389
728
732
605
197
746
762
729
493
1042
764
729
288
729
163
768
732
605
126
731
731
748
197
768
163
731
605
732
762
271
1041
732
605
732
594
1021
719
732
732
605
627
768
163
734
734
213
728
758
534
734
764
746
605
732
1058
735
624
746
758
605
732
735
852
732
605
1064
1041
736
736
1041
721
737
746
736
852
529
1058
1041
512
737
737
721
842
746
930
737
326
737
200
768
163
738
163
768
738
736
1041
738
150
751
163
768
765
739
294
739
732
605
768
739
605
732
271
278
746
741
741
315
762
849
687
741
979
662
474
619
213
742
837
821
742
750
706
742
326
676
734
728
779
746
746
721
737
930
665
746

 71%|███████   | 848/1196 [00:06<00:02, 119.44it/s]

746
677
764
765
605
747
747
952
873
821
750
747
747
737
761
326
842
748
748
762
312
307
741
748
748
1058
1015
732
605
750
750
353
873
747
821
750
750
605
732
769
486
751
1001
751
910
241
771
751
751
677
357
736
731
757
757
762
849
802
307
757
605
732
762
757
146
758
758
728
117
86
24
758
621
605
732
677
142
761
761
345
808
444
339
761
761
200
326
329
930
762
762
849
662
307
271
762
762
746
605
732
771
764
764
493
1042
817
260
764
764
761
746
326
769
765
765
787
126
839
235
765
765
163
768
732
605
768
163
768
332
265
878
768
768
163
765
1064
181
769
769
856
986
888
735
769

 73%|███████▎  | 874/1196 [00:07<00:02, 116.92it/s]

769
746
148
750
849
771
1001
771
910
241
711
771
771
762
732
605
761
777
493
1042
777
1064
764
777
777
768
163
607
953
778
493
1042
778
929
260
778
778
787
793
682
1058
779
779
210
668
688
697
779
796
650
868
197
709
780
780
781
795
687
807
780
780
781
265
795
619
781
781
807
621
687
1024
781
353
664
512
665
596
782
779
213
326
367
200
782
782
918
650
534
619
784
493
1042
784
260
288
784
796
784
781
779
792
785
785
721
267
665
746
785
779
792
786
746
732
786
786
849
687
710
781
786
786
779
796
792
784
787
1001
910
521
797
835
787
353
619
793
431
849
788
332
788
529
792
853
788

 74%|███████▍  | 886/1196 [00:07<00:02, 116.44it/s]

332
788
650
792
535
790
821
790
873
782
747
790
778
781
779
784
792
792
332
792
229
715
286
792
1058
916
535
163
768
793
793
787
839
765
211
793
353
529
1064
213
326
795
795
781
986
687
807
795
594
1021
795
781
1032
796
796
779
781
282
784
796
796
719
270
1058
367
797
721
797
842
737
930
797
288
326
446
440
797
798
332
437
853
878
226
798
1042
493
824
817
260
799
1042
493
799
764
260
799
353
58
120
27
89
800
800
594
1021
1032
807
800
812
807
800
677
621
802
802
849
807
253
1046
802

 76%|███████▌  | 909/1196 [00:07<00:02, 104.72it/s]

802
764
839
814
668
803
1001
803
910
241
603
803
852
948
949
984
946
804
849
804
802
762
307
804
804
799
849
715
683
806
806
427
446
839
211
806
511
817
431
353
808
807
807
600
1046
849
812
807
807
600
812
800
620
808
808
444
1070
854
838
808
677
621
808
824
593
810
631
326
1030
200
86
810
677
621
807
852
836
812
807
812
849
600
687
812
807
812
331
802
621
813
332
813
650
715
853
813
813
855
849
814
839
814
814
493
1042
682
764
814
1042
493
814
764
260
815
800
807
815
852
812
815
815
524
800
807
680
817
493
1042
817
260
764
817
721
817
842
326
761
820

 78%|███████▊  | 934/1196 [00:07<00:02, 111.84it/s]

1042
493
817
764
288
820
332
996
254
948
493
821
821
837
873
742
878
821
444
446
821
677
58
824
1042
493
824
847
260
824
824
1075
831
838
847
826
332
826
529
207
535
826
1042
493
260
288
261
829
829
807
849
831
802
829
829
843
831
337
134
830
493
1042
830
260
764
830
677
621
593
1064
353
831
849
807
831
802
762
831
89
120
58
27
621
832
832
1001
910
711
852
832
832
534
535
661
271
833
833
807
802
500
849
833
833
677
621
838
664
834
332
834
286
715
853
834
834
849
619
713
796
835
835
721
797
851
1082
835

 80%|████████  | 958/1196 [00:07<00:02, 107.01it/s]

835
817
89
120
27
836
836
839
842
665
89
836
677
431
621
778
593
837
837
821
742
353
873
837
837
835
677
621
89
838
838
808
917
854
444
838
677
621
89
120
58
839
721
851
844
842
665
839
1001
910
852
241
711
840
332
840
286
1054
933
840
332
535
440
229
207
841
841
808
854
838
444
841
841
593
328
677
945
842
842
721
58
27
89
842
842
721
737
665
930
843
332
535
163
768
529
843
332
831
829
853
807
844
844
665
27
120
58
844
844
621
677
814
654
845
1001
845
910
711
241
845
808
807
353
852
800
846
846
807
307
849
986
846
332
535
229
163
768
847
1042
493
764
288
260
847
824
847
808
807
852
848

 82%|████████▏ | 985/1196 [00:08<00:02, 104.22it/s]

808
854
848
841
444
848
848
782
326
746
694
849
849
802
804
307
762
849
332
715
683
289
878
851
842
721
851
797
696
851
849
933
353
148
836
852
1001
852
910
241
711
852
326
534
200
213
668
853
332
853
650
878
768
853
332
853
535
878
226
854
854
808
339
444
345
854
1044
808
807
238
846
855
1042
493
855
1064
764
855
855
845
849
799
650
856
856
486
860
462
876
856
769
856
958
368
836
859
271
852
867
353
511
859
873
859
879
885
888
860
1042
493
860
764
260
860
493
1042
860
764
652
867

 83%|████████▎ | 996/1196 [00:08<00:02, 90.54it/s]

867
213
345
311
888
867
867
326
213
842
120
868
332
868
650
718
449
868
868
561
431
1058
836
873
867
873
852
326
353
873
1041
619
852
856
898
876
876
765
524
386
233
876
876
677
856
486
621
878
878
821
873
684
1027
878
621
677
878
431
211
879
879
721
27
120
89
879
126
873
879
888
856
881
881
163
768
856
876
881
881
522
220
331
876
885
885
910
1020
145
428
885
885
209
867
176
474
888

 85%|████████▌ | 1017/1196 [00:08<00:01, 90.93it/s]

888
326
867
213
224
888
213
677
621
761
958
898
898
536
808
444
841
898
1042
493
764
842
721
904
904
768
163
732
605
904
719
904
605
732
197
909
332
909
265
878
996
909
979
982
975
948
1041
910
885
910
1020
145
428
910
910
885
176
921
425
913
913
873
782
706
821
913
921
849
979
929
842
914
914
762
849
307
354
914
914
933
353
326
849
915
493
1042
915
61
30
915
594
1021
509
852
796
916
1001
910
916
711
852
916
916
197
474
852
529
917
917
808
926
924
444
917
917
513
553
621
1046
918
876
765
930
904
211
918
918
750
876
127
860
921
849
762
246
307
1046
921
1021
594
914
933
928
924

 87%|████████▋ | 1043/1196 [00:08<00:01, 106.66it/s]

924
808
339
926
444
924
914
1058
933
928
719
925
925
326
200
213
177
925
326
213
200
677
721
926
926
808
444
339
924
926
677
621
593
511
829
928
928
914
933
353
326
928
928
921
619
929
849
929
493
1042
929
260
764
929
929
553
513
817
269
930
721
930
842
245
665
930
721
930
737
746
89
933
933
332
226
391
229
933
933
255
213
474
765
935
914
353
933
326
368
935
935
916
166
852
474
937
1001
910
852
937
551
937
353
593
474
677
621
939
939
144
665
962
1045
939
677
621
593
353
1041
940
1041
940
172
721
946
940
721
1041
904
1067
665
941
493
1042
941
996
1013
941
493
1042
1064
764
941
943
943
849
986
343
762
943
943
163
768
999
337
945

 90%|████████▉ | 1071/1196 [00:09<00:01, 118.71it/s]

945
953
841
328
984
945
953
945
328
841
996
946
946
721
969
980
665
946
946
1042
493
1041
980
948
1042
493
948
949
764
948
949
677
621
593
353
949
949
493
1042
948
996
949
949
808
1013
616
417
950
665
946
950
721
969
950
677
621
593
1041
852
952
952
873
417
353
821
952
984
852
946
952
949
953
953
668
779
676
326
953
953
945
979
841
1065
954
493
1042
1013
954
948
954
665
1045
616
982
1013
957
984
852
946
986
982
957
952
110
48
79
17
958
958
200
326
305
817
958
677
958
979
764
984
962
962
616
326
555
198
962
962
939
619
768
163
965
965
849
762
1046
986
965
965
768
163
949
796
969
969
980
946
721
1085
969
969
980
975
979
986
970
1001
140
910
970
852
970
852
1041
761
619
271
972

 92%|█████████▏| 1099/1196 [00:09<00:00, 125.20it/s]

332
972
265
996
948
972
332
996
529
972
265
973
1041
665
721
267
785
973
973
594
1021
619
431
975
975
808
982
1065
761
975
980
979
969
975
986
979
979
1001
980
910
1080
979
979
980
969
975
986
980
980
969
946
979
975
980
980
979
969
975
949
982
982
926
975
808
444
982
982
353
126
1022
596
984
984
946
952
982
975
984
1058
984
619
982
975
986
986
980
984
975
969
986
980
986
975
969
979
996
332
996
878
948
972
996
982
975
680
986
984
998
998
235
839
1047
765
998
998
1058
353
849
326
999
999
1015
1053
628
591
999
677
621
431
593
999
1001
1001
910
176
711
241
1001
677
621
910
1001
593
1004
1041
1004
209
721
120
1004
1041
1013
852
238
326
1005
852
1041
436
824
808
1005
211
852
353
1041
206
1007

 94%|█████████▍| 1128/1196 [00:09<00:00, 130.16it/s]

1021
594
1032
1007
353
1007
677
1007
719
594
1021
1008
1008
873
617
270
1050
1008
126
89
120
27
58
1013
1013
1042
493
948
764
1013
172
721
1041
665
234
1015
1001
910
335
1015
347
1015
220
126
1007
665
1001
1017
1017
326
669
758
642
1017
731
1084
190
1017
317
1019
1019
852
1058
1064
326
1019
1019
644
916
197
524
1020
1020
1001
1052
215
560
1020
1020
1001
910
885
347
1021
594
1021
690
380
629
1021
594
1021
719
380
509
1022
596
1022
719
326
353
1022
594
1021
732
605
629
1024
1024
354
601
807
621
1024
687
1024
601
354
762
1026
1026
298
282
343
322
1026
1058
1052
317
1043
808
1027
873
1027
821
353
417
1027
621
677
1041
209
593
1029
1029
1046
307
807
331
1029
1029
719
1052
1013
335
1030
1030
171
389
660
202
1030
1030
677
1058
621
1041
1032

 97%|█████████▋| 1157/1196 [00:09<00:00, 130.35it/s]

594
1021
1032
380
800
1032
677
621
619
593
1032
1033
1041
1042
762
852
332
1033
621
677
1033
1032
593
1035
353
873
1035
952
362
1035
660
529
1043
653
683
1039
1039
808
619
854
1052
1039
677
621
1058
619
1039
1040
1040
312
334
629
1047
1040
1040
1058
353
213
317
1041
1041
736
721
267
27
1041
1041
852
660
353
1032
1042
1042
493
288
996
1013
1042
1042
1056
762
332
232
1043
1043
878
1027
1035
873
1043
1043
873
821
1035
1058
1044
1042
493
1044
238
764
1044
1044
235
439
1058
852
1045
1045
808
339
444
619
1045
1045
621
677
593
1013
1046
1046
807
307
498
600
1046
1046
260
513
553
498
1047
1047
998
235
839
765
1047
1001
910
335
512
711
1050
1050
873
220
176
353
1050
1050
644
1017
353
1001
1052
1052
808
1039
339
444
1052

 99%|█████████▉| 1185/1196 [00:09<00:00, 123.87it/s]

27
120
89
58
1052
1053
1001
910
335
317
711
1053
1053
683
1039
354
1024
1054
332
1054
529
535
718
1054
1046
817
644
513
553
1056
1056
1075
1070
288
446
1056
1075
1056
1070
353
1058
1058
1058
873
353
821
684
1058
1056
796
1067
1058
271
1060
975
1065
1060
808
1070
1060
677
621
852
619
761
1064
1075
1070
1056
746
326
1064
1056
1075
1070
677
621
1065
1065
808
982
975
1060
1065
1080
1065
1058
1060
984
1067
1067
721
574
1082
665
1067
1067
619
1058
1056
624
1070
1070
808
1075
444
926
1070
1056
1075
1070
621
677
1075
1001
910
335
711
661
1075
1075
1056
1070
1058
1064
1077
808
761
982
444
1070
1077
949
534
1077
353
326
1080

100%|██████████| 1196/1196 [00:10<00:00, 119.52it/s]

1001
910
1080
979
512
1080
996
1056
948
984
796
1082
1082
721
835
737
665
1082
353
521
126
619
949
1084
1084
190
952
873
821
1084
677
190
1084
1017
621
1085
1085
980
969
721
1041
1085
1058
1056
949
1067
619
1087
1087
721
746
930
851
1087
1087
1058
1056
1064
238

In [92]:
def hit_rate(relevance):
    cnt = 0

    for line in relevance:
        if 1 in line:
            cnt = cnt + 1

    return cnt / len(relevance)

In [93]:
relevance_total[:30]

[[1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0]]

In [94]:
hit_rate(relevance_total)

0.7332775919732442

In [69]:
len(relevance_total)

1196

In [67]:
def mrr(relevance):
    total_score = 0.0

    for line in relevance:
        for rank in range(len(line)):
            if line[rank] == 1:
                score = 1 / (rank + 1)
                total_score = total_score + score
                break

    return total_score / len(relevance)

In [68]:
mrr(relevance_total)

0.0

In [42]:
def evaluate(ground_truth, search_function):
    relevance_total = compute_relevance_total(ground_truth, search_function)

    return {
        "hit_rate": hit_rate(relevance_total),
        "mrr": mrr(relevance_total),
    }

In [43]:
evaluate(ground_truth, text_search)

100%|██████████| 1196/1196 [00:07<00:00, 153.37it/s]

{'hit_rate': 0.0, 'mrr': 0.0}

In [45]:
df_validation = df_ground_truth[:700]
df_test = df_ground_truth[700:]

gt_val = df_validation.to_dict(orient="records")
gt_test = df_test.to_dict(orient="records")

In [46]:
def search_boosts(query, recipe_name_boost, ingredients_boost, nutrition_boost):
    boost_dict = {
        "recipe_name": recipe_name_boost,
        "ingredients": ingredients_boost,
        "nutrition": nutrition_boost,
    }

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict,
    )

In [47]:
results = []

for recipe_name_boost in [0.5, 1.0, 2.0, 3.0]:
    for ingredients_boost in [0.5, 1.0, 2.0, 5.0, 10.0]:
        for nutrition_boost in [0.5, 1.0, 3.0]:
            print(f"Evaluating recipe_name_boost={recipe_name_boost}, ingredients_boost={ingredients_boost}, nutrition_boost={nutrition_boost}...")
            result = evaluate(
                gt_val,
                lambda query, recipe_name_boost=recipe_name_boost, ingredients_boost=ingredients_boost, nutrition_boost=nutrition_boost: search_boosts(
                    query,
                    recipe_name_boost,
                    ingredients_boost,
                    nutrition_boost
                )
            )

            results.append({
                "recipe_name": recipe_name_boost,
                "ingredients": ingredients_boost,
                "nutrition": nutrition_boost,
                "hit_rate": result["hit_rate"],
                "mrr": result["mrr"],
            })

Evaluating recipe_name_boost=0.5, ingredients_boost=0.5, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 144.44it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=0.5, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 152.53it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=0.5, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 155.70it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=1.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 149.63it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=1.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 157.78it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=1.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:05<00:00, 135.64it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=2.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 161.67it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=2.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 157.40it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=2.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 161.88it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=5.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 163.18it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=5.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 157.80it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=5.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 163.15it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=10.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 159.97it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=10.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 164.08it/s]

Evaluating recipe_name_boost=0.5, ingredients_boost=10.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 164.41it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=0.5, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 153.84it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=0.5, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 167.08it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=0.5, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 158.31it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=1.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 160.40it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=1.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 160.51it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=1.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 161.87it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=2.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 165.11it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=2.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 155.29it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=2.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 146.81it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=5.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 149.51it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=5.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 160.43it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=5.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 152.63it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=10.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:11<00:00, 63.52it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=10.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:06<00:00, 101.87it/s]

Evaluating recipe_name_boost=1.0, ingredients_boost=10.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 145.30it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=0.5, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 165.66it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=0.5, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 157.75it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=0.5, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 161.10it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=1.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 157.48it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=1.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 164.58it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=1.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 157.48it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=2.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 159.99it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=2.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 164.39it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=2.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 159.53it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=5.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 166.94it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=5.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 157.70it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=5.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 146.00it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=10.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 161.14it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=10.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 156.40it/s]

Evaluating recipe_name_boost=2.0, ingredients_boost=10.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 161.86it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=0.5, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 159.24it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=0.5, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 150.93it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=0.5, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 156.29it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=1.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:05<00:00, 131.15it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=1.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 155.33it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=1.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 159.34it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=2.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 151.12it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=2.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 157.00it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=2.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 163.66it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=5.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 157.55it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=5.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 167.21it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=5.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 158.02it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=10.0, nutrition_boost=0.5...

100%|██████████| 700/700 [00:04<00:00, 164.95it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=10.0, nutrition_boost=1.0...

100%|██████████| 700/700 [00:04<00:00, 163.28it/s]

Evaluating recipe_name_boost=3.0, ingredients_boost=10.0, nutrition_boost=3.0...

100%|██████████| 700/700 [00:04<00:00, 159.65it/s]

In [49]:
df_results = pd.DataFrame(results)
df_results.sort_values("mrr", ascending=False).head(10)

   recipe_name  ingredients  nutrition  hit_rate  mrr
0          0.5          0.5        0.5       0.0  0.0
1          0.5          0.5        1.0       0.0  0.0
2          0.5          0.5        3.0       0.0  0.0
3          0.5          1.0        0.5       0.0  0.0
4          0.5          1.0        1.0       0.0  0.0
5          0.5          1.0        3.0       0.0  0.0
6          0.5          2.0        0.5       0.0  0.0
7          0.5          2.0        1.0       0.0  0.0
8          0.5          2.0        3.0       0.0  0.0
9          0.5          5.0        0.5       0.0  0.0